version: '1.0'
services:
  mysql:
    image: mysql
    container_name: fastapi_graphqlDb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    
